### ISSUE TITLE
Updating docker image

### ISSUE THREAD

**Issue by Dekken** [RadeonOpenCompute/ROCm-docker#26]
Is there an ETA for this?

I'd rather not have to run  ```apt-get dist-upgrade```  every time I launch a container.

Is there somehow to keep persistent containers?

**Comment by kknox** [comment]
I don't follow your question yet.  Are you looking for pre-built ROCm docker images?  You could try:
https://hub.docker.com/r/rocm/hip-hcc-ctu-ubuntu-16.04/
https://hub.docker.com/r/rocm/dev-fedora-24/

These are ROCm 1.6.4 images,

**Comment by Dekken** [comment]
If one is to follow the current instructions on this repo to download the docker image, a further 300+ MB is required when running "apt-get update && apt-get dist-upgrade"

in order to retrieve the lastest versions of 

```
rocm-user@f22ed030d469:~$ sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  cxlactivitylogger rocm-profiler
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  hsa-amd-aqlprofile hsakmt-roct rocm-clang-ocl rocm-opencl rocm-opencl-dev rocminfo
The following packages will be upgraded:
  curl cxlactivitylogger dpkg hcc hip_base hip_doc hip_hcc hip_samples hsa-ext-rocr-dev hsa-rocr-dev hsakmt-roct-dev libcurl3-gnutls libdb5.3 libgnutls30 libperl5.22 libsystemd0 libudev1 linux-libc-dev perl perl-base perl-modules-5.22
  rocm-dev rocm-device-libs rocm-profiler rocm-smi rocm-utils systemd systemd-sysv
28 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 373 MB of archives.
After this operation, 344 MB of additional disk space will be used.
```

My query, is would it be possible to update the docker image to include these updates

**Comment by kknox** [comment]
I'm closer to understanding.  AMD released Ubuntu packages for v1.7 ROCm on [repo.radeon.com](http://repo.radeon.com/) a few weeks ago.  I'm ignoring the **dist-upgrade** portion of your update command, because we only officially support Ubuntu 16.04.  I think those are the new ROCm packages you see above.  However, we have not released the Fedora v1.7 packages yet.  

So, I have been hesitant to push the updated Ubuntu docker image while keeping the Fedora docker image behind.  I figured I would wait until both distro's were on the same release, but you are want Ubuntu image now.

Are you comfortable building your own dockerfile?  You can use this [Dockerfile-ubuntu-16.04](https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/dev/Dockerfile-ubuntu-16.04) to build your own image of Ubuntu ROCm v1.7.  This is the same dockerfile I use to update the image on [docker hub](https://hub.docker.com/r/rocm/dev-ubuntu-16.04/)

**Comment by twobombs** [comment]
Also, one can use docker-squash to deduplicate the docker image after apt-get / dist- upgrade

**Comment by Dekken** [comment]
@twobombs @kknox thanks that's helpful
